# name: "Run Project"
# on: [push]

# jobs:
#   setup:
    
#     name: Setup Bun
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup Bun
        
#         # You may pin to the exact commit or the version.
#         uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135
#         # uses: oven-sh/setup-bun@v1
#         with:
#           working-directory: /home/runner/work/vintage-story-calculators/vintage-story-calculators
#           # The version of Bun to install. (e.g. "latest", "canary", "1.0.0", "1.0.x", <sha>)
#           bun-version: "latest"
#           no-cache: "false"
#       - name: List
#         run: |
#           ls ${{ github.workspace }}
#           cd ${{ github.workspace }}
#           ls
#           pwd
#       - name: Test
#         working-directory: /home/runner/work/vintage-story-calculators/vintage-story-calculators
#         run: |
#           cd ../
#           bun install
#           bun run test


name: my-workflow
on: [push]
jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun run test
