- name: Setup Bun
- on:
   push:
    branches:
     -main
- uses: oven-sh/setup-bun@v1.2.1
   with:
     # The version of Bun to install. (e.g. "latest", "canary", "1.0.0", "1.0.x", <sha>)
     bun-version: "latest"
     # The URL of the package registry to use for installing Bun. Set the $BUN_AUTH_TOKEN environment variable to authenticate with the registry.
     registry-url: "https://npm.pkg.github.com/"
  
