name: "Setup Bun"
on: [push]

jobs:
  setup:
    name: Setup Bun
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135
        with:
         bun-version: "latest"

